// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpK9Enyj_wp780r5_b0FSc7OUSJ8kenoQ',
    appId: '1:252165468472:android:f19d8eecf1cd3e1faa91cd',
    messagingSenderId: '252165468472',
    projectId: 'ecomm-app-33b72',
    storageBucket: 'ecomm-app-33b72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdsrQsJz1yGv0rtUKKeJBs8jRJSd5KPs',
    appId: '1:252165468472:ios:bc8343140fadb36eaa91cd',
    messagingSenderId: '252165468472',
    projectId: 'ecomm-app-33b72',
    storageBucket: 'ecomm-app-33b72.appspot.com',
    androidClientId: '252165468472-uduil7adrmg026tpepd437he7bvisfbd.apps.googleusercontent.com',
    iosClientId: '252165468472-3buu0mjmnk93esvq262oombv7im6pj7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiBpXDLq3Q_MOwMMxKXsIVy3EoQqkDaJA',
    appId: '1:252165468472:web:e36f1f26f76c27b1aa91cd',
    messagingSenderId: '252165468472',
    projectId: 'ecomm-app-33b72',
    authDomain: 'ecomm-app-33b72.firebaseapp.com',
    storageBucket: 'ecomm-app-33b72.appspot.com',
    measurementId: 'G-4DG2R5M986',
  );

}